export const StudientData = [
  {
    id: 1,
    nom: "garciaco",
    prenom: "diego",
    ville: "paris 12",
    lat: 48.862725,
    long: 2.287592,
    hobbies: "serie / lecture",
    music: "rock latino / musique regionale nord mexique",
    sport: "marche",
    jv: "je joue pas ",
    serie: "el chapo",
    manga: "",
    plat: "enchiladas suizas",
    boisson: "cafe et the",
    alcool: "spritz",
    entreprise: "neosoft",
    stack: "react / typescript / nodejs / .net",
  },
  {
    id: 2,
    nom: "carpentier",
    prenom: "audrey",
    ville: "fitz-james",
    lat: 49.3918395,
    long: 2.4283593,
    hobbies: "jeux video / manga / musique",
    music: "metal / classique / bachata",
    sport: "",
    jv: "phasmaphobia",
    serie: "ly name is earl  / lazy company",
    manga: "",
    plat: "crepe sous toutes ses formes / crepe nutella",
    boisson: "capuccino noisette",
    alcool: "",
    entreprise: "",
    stack: "reactjs / nodejs",
  },
  {
    id: 3,
    nom: "el azzati",
    prenom: "yassine",
    ville: "arras",
    lat: 50.291048,
    long: 2.7772211,
    hobbies: "jeux video / sports de combat / chats",
    music: "hip-hop",
    sport: "sports de combat",
    jv: "valorant",
    serie: "",
    manga: "",
    plat: "",
    boisson: "the marocain",
    alcool: "coca pur",
    entreprise: "regional express",
    stack: "angular / spring-boot",
  },
  {
    id: 4,
    nom: "mortelette",
    prenom: "thomas",
    ville: "lille (vieux lille)",
    lat: 50.6441472,
    long: 3.0603388,
    hobbies: "cinema / dev / espace",
    music: "electro / dub / hip-hop",
    sport: "musculation de doigt au clavier",
    jv: "fps / mmorpg / horreur",
    serie: "horreur",
    manga: "attack on titan / fullmetal achemist",
    plat: "tartiflette",
    boisson: "cafe noir",
    alcool: "biere fruit",
    entreprise: "parkking",
    stack: "angular / vuejs / synfony",
  },
  {
    id: 5,
    nom: "laskari",
    prenom: "zakaria",
    ville: "roubaix",
    lat: 50.6915893,
    long: 3.1741734,
    hobbies: "sport / manga / jeux video",
    music: "le son clavier",
    sport: "foot / basket / boxe",
    jv: "league of legend / counter strike",
    serie: "prison break",
    manga: "dragon ball",
    plat: "tajine",
    boisson: "the marocain",
    alcool: "eau pur",
    entreprise: "degetel",
    stack: "react / synfony",
  },
  {
    id: 6,
    nom: "fraisse",
    prenom: "pierre",
    ville: "lille (bois-blanc)",
    lat: 50.633315,
    long: 3.031575,
    hobbies: "musique / sport / cinema",
    music: "selon l'humeur / soul funk 70 / rap 90",
    sport: "boxe thai / fitness / course a pied",
    jv: "rarement",
    serie: "the bear",
    manga: "blame!",
    plat: "pizza italiano pur sang",
    boisson: "cafe",
    alcool: "scotish whisky tourbé mais pas trop ",
    entreprise: "recygroup",
    stack: "angular / .net",
  },
  {
    id: 7,
    nom: "lafrance",
    prenom: "camille",
    ville: "paris mantsouris",
    lat: 48.8588897,
    long: 2.320041,
    hobbies:
      "cinema / poadcast(sur le cinema et politique) / lecture / jeux de societe",
    music: "",
    sport: "quad / yoga / s'occuper de mon chat",
    jv: "pas du tout",
    serie: "seinfeild / brocklyn nine nine",
    manga: "nana",
    plat: "bonne salade composee / cuisine asitaique",
    boisson: "cafe au lait sucree",
    alcool: "spritz / tequilla sunrise / vin blanc",
    entreprise: "courir",
    stack: "react / angular / typescript / spring-boot / nodejs / swift",
  },
  {
    id: 8,
    nom: "moreschi",
    prenom: "jonathan",
    ville: "gretz-armainvilliers",
    hobbies: "jeux video / lecture / myrmecologie",
    lat: 48.73333,
    long: 2.73333,
    music: "",
    sport: "",
    jv: "civilization / crusader king / STR",
    serie: "kamelott / weed",
    manga: "tout",
    plat: "tartiflette",
    boisson: "the",
    alcool: "pastis / vin rouge",
    entreprise: "gestimo",
    stack: "php / laravel / flutter / reactjs / nextjs / nodejs",
  },
  {
    id: 9,
    nom: "foucher",
    prenom: "alexandre",
    ville: "valenciennes",
    lat: 50.357113,
    long: 3.518332,
    hobbies: "music / jeux video / manga / anime",
    music: "electro / metal / classique",
    sport: "try hard les apm",
    jv: "STR / civilization",
    serie: "",
    manga: "darwin's game / stein gate",
    plat: "tartiflette",
    boisson: "the",
    alcool: "biere / whisky",
    entreprise: "lyreco",
    stack: "reactjs / java / nodejs / php / vb.net",
  },
  {
    id: 10,
    nom: "pierson",
    prenom: "theo",
    ville: "lestrem",
    lat: 50.616669,
    long: 2.68333,
    hobbies: "lecture / film / serie / sport de combat",
    music: "rap",
    sport: "sport de combat",
    jv: "non je ne joue pas",
    serie: "games of thrones",
    manga: "one piece / baki",
    plat: "curry japonais avec porc croquant",
    boisson: "cafe",
    alcool: "biere et rhum mais je suis censé arreter waow",
    entreprise: "sister company",
    stack: "react / angular / sring-boot",
  },
  {
    id: 11,
    nom: "chauvin",
    prenom: "melanie",
    lat: 50.6424441,
    long: 3.088507,
    ville: "lille (saint-maurice pelvoisin)",
    hobbies: "rando / manger / champagne",
    music: "",
    sport: "taekwondo",
    jv: "",
    serie: "",
    manga: "",
    plat: "le poulet sous toutes ses formes",
    boisson: "cafe bien noir",
    alcool: "veuve cliquot / jamaican mule",
    entreprise: "wiiisdom",
    stack: "vuejs / angular / quarkus",
  },
  {
    id: 12,
    nom: "deflandre",
    prenom: "nassim",
    ville: "ronchin",
    hobbies: "sport / serie / passer du temps en famille",
    music: "rap",
    sport: "judo / foot",
    jv: "fifa / call of duty",
    serie: "vikings / power",
    manga: "avatar le maitre de l'air",
    plat: "couscous",
    boisson: "cafe",
    alcool: "cristaline pur",
    entreprise: "cegid",
    stack: "reactjs / nodejs / .net",
  },
  {
    id: 13,
    nom: "phounphonh",
    prenom: "ludovic",
    lat: 50.566669,
    long: 3.05,
    ville: "templemars",
    hobbies: "manger / boire / ballade / moto / musique",
    music: "metal / classique / de tout",
    sport: "ballade avec le chien",
    jv: "jeux campagne solo",
    serie: "kamelott",
    manga: "one piece / hellsing / berserk",
    plat: "tout",
    boisson: "cafe",
    alcool: "tout",
    entreprise: "proxiad",
    stack: "reactjs / react native / angular / spring / nodejs",
  },
  {
    id: 14,
    nom: "beauvois",
    prenom: "marine",
    ville: "la madeleine",
    lat: 50.650002,
    long: 3.06667,
    hobbies: "sport / ecouter poadcast (relation humaine)",
    music: "de tout / commerciale",
    sport: "bodypump / fitness / cardio",
    jv: "zelda / mario",
    serie: "drama indien / asiatique",
    manga: "shojo / marvel comics",
    plat: "cuisine asiatique",
    boisson: "the chai",
    alcool: "cocktail",
    entreprise: "darmart",
    stack: "cobol / ruby / rex",
  },
];
