export const StudientData = [
  {
    id: 1,
    nom: "garciaco",
    prenom: "diego",
    ville: "paris 12",
    latlong: [48.8408156, 2.388369],
    hobbies: "serie / lecture",
    music: "rock latlongino / musique regionale nord mexique",
    sport: "marche",
    jv: "je joue pas ",
    serie: "el chapo",
    manga: "",
    platlong: "enchiladas suizas",
    boisson: "cafe et the",
    alcool: "spritz",
    entreprise: "neosoft",
    stack: "react / typescript / nodejs / .net",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQExjG2BaPALWA/profile-displayphoto-shrink_800_800/0/1675516572257?e=1701302400&v=beta&t=Nvug3IgmLWn0W0MBzymBU5RdEySWmXJKnQ2ZRniMfRM",
    linkedin: "https://www.linkedin.com/in/diego-garciaco",
    github: "https://github.com/dgo-gco",
  },
  {
    id: 2,
    nom: "carpentier",
    prenom: "audrey",
    ville: "fitz-james",
    latlong: [49.3918395, 2.4283593],
    hobbies: "jeux video / manga / musique",
    music: "metal / classique / bachata",
    sport: "inscrite en salle",
    jv: "phasmaphobia",
    serie: "my name is earl / lazy company",
    manga: "j'aime pas les mangas",
    platlong: "crepe sous toutes ses formes / crepe nutella",
    boisson: "capuccino noisette",
    alcool: "cocktail / spritz / margaritta fraise / mojitos",
    entreprise: "keep:api",
    stack: "reactjs / nodejs",
    photo:
      "https://media.licdn.com/dms/image/D4E35AQFE7Z-bzdobew/profile-framedphoto-shrink_800_800/0/1672698193779?e=1695996000&v=beta&t=Pir_Rwd0Q5nJzyPouWHG6vMNRTfrkvBS9K7_BI3Z4BE",
    linkedin: "https://www.linkedin.com/in/audrey3010/",
    github: "https://github.com/AudreyAAOO",
  },
  {
    id: 3,
    nom: "el azzati",
    prenom: "yassine",
    ville: "arras",
    latlong: [50.291048, 2.7772211],
    hobbies: "jeux video / sports de combat / chats",
    music: "hip-hop",
    sport: "sports de combat",
    jv: "valorant",
    serie: "",
    manga: "Hunter x Hunter",
    platlong: "Tajine olive",
    boisson: "the marocain",
    alcool: "coca pur",
    entreprise: "regional express",
    stack: "angular / spring",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQESvYIHXHd8sQ/profile-displayphoto-shrink_800_800/0/1683528669553?e=1700697600&v=beta&t=jA4KOB0TSa6pNyEiPJYOctC4X6fFdXfmpkWP_ceIpb8",
    linkedin: "https://www.linkedin.com/in/yassine-el-azzati-7b5a331b8/",
    github: "https://github.com/YassineElazzati",
  },
  {
    id: 4,
    nom: "mortelette",
    prenom: "thomas",
    ville: "lille (vieux lille)",
    latlong: [50.6441472, 3.0603388],

    hobbies: "cinema / dev / espace",
    music: "electro / dub / hip-hop",
    sport: "musculatlongion de doigt au clavier",
    jv: "fps / mmorpg / horreur",
    serie: "horreur",
    manga: "attack on titan / fullmetal achemist",
    platlong: "tartiflette",
    boisson: "cafe noir",
    alcool: "biere fruit",
    entreprise: "parkking",
    stack: "angular / vuejs / synfony",
    photo:
      "https://media.licdn.com/dms/image/C4E03AQEHgl7zMrio8g/profile-displayphoto-shrink_800_800/0/1614677595219?e=1700697600&v=beta&t=mlYJPJvNIC_uxkjyeIWd1YobyvPa1MJ4InScceJ_6uo",
    linkedin: "https://www.linkedin.com/in/thomas-mortelette-845318190/",
    github: "https://github.com/DKHexDev",
  },
  {
    id: 5,
    nom: "laskari",
    prenom: "zakaria",
    ville: "roubaix",
    latlong: [50.6915893, 3.1741734],
    hobbies: "sport / manga / jeux video",
    music: "le son clavier",
    sport: "foot / basket / boxe",
    jv: "league of legend / counter strike",
    serie: "prison break",
    manga: "dragon ball",
    platlong: "tajine",
    boisson: "the marocain",
    alcool: "eau pur",
    entreprise: "degetel",
    stack: "react / synfony",
    photo:
      "https://media.licdn.com/dms/image/D4E35AQGFQZZYCOeSKw/profile-framedphoto-shrink_800_800/0/1680608441498?e=1695996000&v=beta&t=rARGfCz1WtY055JUnFGe8khQByJywizZRgJDoA-Styg",
    linkedin: "https://www.linkedin.com/in/zakaria-laskari/",
    github: "https://github.com/zakkios",
  },
  {
    id: 6,
    nom: "fraisse",
    prenom: "pierre",
    ville: "lille (bois-blanc)",
    latlong: [50.6295089398497, 3.0211810062599875],
    hobbies: "musique / sport / cinema",
    music: "selon l'humeur / soul funk 70 / rap 90",
    sport: "boxe thai / fitness / course a pied",
    jv: "rarement",
    serie: "the bear",
    manga: "blame!",
    platlong: "pizza italiano pur sang",
    boisson: "cafe",
    alcool: "scotish whisky tourbé mais pas trop ",
    entreprise: "recygroup",
    stack: "angular / .net",
    photo:
      "https://media.licdn.com/dms/image/D5603AQFTWWLF3oQh0g/profile-displayphoto-shrink_800_800/0/1665496487126?e=1700697600&v=beta&t=mM1OSwpVxUTXQytrszjqMUckKZfW9ZrsRRBYGiD_Doc",
    linkedin: "https://www.linkedin.com/in/pierre-fraisse-83b4b5253/",
    github: "https://github.com/PierreFrs",
  },
  {
    id: 7,
    nom: "lafrance",
    prenom: "camille",
    ville: "paris mantsouris",
    latlong: [48.8588897, 2.320041],
    hobbies:
      "cinema / poadcast(sur le cinema et politique) / lecture / jeux de societe",
    music: "",
    sport: "quad / yoga / s'occuper de mon chat",
    jv: "pas du tout",
    serie: "seinfeild / brocklyn nine nine",
    manga: "nana",
    platlong: "bonne salade composee / cuisine asitaique",
    boisson: "cafe au lait sucree",
    alcool: "spritz / tequilla sunrise / vin blanc",
    entreprise: "courir",
    stack: "react / angular / typescript / spring-boot / nodejs / swift",
    photo:
      "https://media.licdn.com/dms/image/C4D03AQGR3N7oPtWBXg/profile-displayphoto-shrink_800_800/0/1612951907708?e=1700697600&v=beta&t=thN0nOuPPeF3P1vM8vaVnpYP9y_C1vzsl6eMLOiK-EU",
    linkedin: "https://www.linkedin.com/in/camille-m-lafrance/",
    github: "https://github.com/CamilleLafrance/",
  },
  {
    id: 8,
    nom: "moreschi",
    prenom: "jonathan",
    ville: "gretz-armainvilliers",
    latlong: [48.7410407, 2.7359603],
    hobbies: "jeux video / lecture / myrmecologie",
    music: "metal / funk / soul",
    sport: "",
    jv: "civilization / crusader king / STR",
    serie: "kamelott / weed",
    manga: "tout",
    platlong: "tartiflette",
    boisson: "the",
    alcool: "pastis / vin rouge",
    entreprise: "gestimo",
    stack: "php / laravel / flutter / reactjs / nextjs / nodejs",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQGHN9PQU5oL0g/profile-displayphoto-shrink_800_800/0/1678267418185?e=1700697600&v=beta&t=tMt7i7wGJZWiZlijtgOGdTh2r1ybpIMWsAasrPoC8Wc",
    linkedin: "https://www.linkedin.com/in/jomoreschi/",
    github: "https://github.com/Eromnoj",
  },
  {
    id: 9,
    nom: "foucher",
    prenom: "alexandre",
    ville: "valenciennes",
    latlong: [50.3579317, 3.5234846],
    hobbies: "music / jeux video / manga / anime",
    music: "electro / metal / classique",
    sport: "try hard les apm",
    jv: "STR / civilization",
    serie: "",
    manga: "darwin's game / stein gate",
    platlong: "tartiflette",
    boisson: "the",
    alcool: "biere / whisky",
    entreprise: "lyreco",
    stack: "reactjs / java / nodejs / php / vb.net",
    photo:
      "https://media.licdn.com/dms/image/C4D03AQEhSrs2F8Kv1w/profile-displayphoto-shrink_800_800/0/1646907985243?e=1700697600&v=beta&t=4J_IcYT2egnYomU84P2XFF2josLGYsh6m8f_lXN1xto",
    linkedin: "https://www.linkedin.com/in/alexandre-foucher-0050571a4/",
    github: "https://github.com/AlexTakoDev",
  },
  {
    id: 10,
    nom: "pierson",
    prenom: "theo",
    ville: "lestrem",
    latlong: [50.6216212, 2.6857534],
    hobbies: "lecture / film / serie / sport de combat",
    music: "rap",
    sport: "sport de combat",
    jv: "non je ne joue pas",
    serie: "games of thrones",
    manga: "one piece / baki",
    platlong: "curry japonais avec porc croquant",
    boisson: "cafe",
    alcool: "biere et rhum mais je suis censé arreter waow",
    entreprise: "sister company",
    stack: "react / angular / sringgit add . ",
    photo:
      "https://media.licdn.com/dms/image/D4E35AQE_4D4H8IdwzQ/profile-framedphoto-shrink_800_800/0/1687850989081?e=1695996000&v=beta&t=Qzx0hnJ0L3p9W7EjS7PN1Ey-tbkJ9Gi984f64NeG7nU",
    linkedin: "",
    github: "https://github.com/TheoPIERSON",
  },
  {
    id: 11,
    nom: "chauvin",
    prenom: "melanie",
    ville: "lille (saint-maurice pelvoisin)",
    latlong: [50.638983, 3.075714],
    hobbies: "rando / manger / champagne",
    music: "electro / dubstep / musique de bar",
    sport: "taekwondo",
    jv: "les sims",
    serie: "youtube oceanne",
    manga: "la docs sur la tech et de temps en temps des thriller polar",
    platlong: "le poulet sous toutes ses formes",
    boisson: "cafe bien noir",
    alcool: "veuve cliquot / jamaican mule",
    entreprise: "wiiisdom",
    stack: "vuejs / angular / quarkus",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQFYZ33KFZxxNQ/profile-displayphoto-shrink_800_800/0/1682181015546?e=1700697600&v=beta&t=0gPt_An2vNt-gfR5gsdV8MgpYTpa-mChN-LVD_SvrVY",
    linkedin: "https://www.linkedin.com/in/melanie-cn/",
    github: "https://github.com/Melcn",
  },
  {
    id: 12,
    nom: "deflandre",
    prenom: "nassim",
    ville: "ronchin",
    latlong: [50.6056749, 3.0778827],
    hobbies: "sport / serie / passer du temps en famille",
    music: "rap",
    sport: "judo / foot",
    jv: "fifa / call of duty",
    serie: "vikings / power",
    manga: "avatar le maitre de l'air",
    platlong: "couscous",
    boisson: "cafe",
    alcool: "cristaline pur",
    entreprise: "cegid",
    stack: "reactjs / nodejs / .net",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQHJpGBpfo6hEQ/profile-displayphoto-shrink_800_800/0/1692090102840?e=1700697600&v=beta&t=RYaJffYPQnqVLXsIaTLiezUhvgEPVUYw8ZJtcjutwk4",
    linkedin: "https://www.linkedin.com/in/nassim-d-aaa48a204/",
    github: "https://github.com/NassJs",
  },
  {
    id: 13,
    nom: "phounphonh",
    prenom: "ludovic",
    ville: "templemars",
    latlong: [50.5762334, 3.0528537],
    hobbies: "manger / boire / ballade / moto / musique",
    music: "metal / classique / de tout",
    sport: "ballade avec le chien",
    jv: "jeux campagne solo",
    serie: "kamelott",
    manga: "one piece / hellsing / berserk",
    platlong: "tout",
    boisson: "cafe",
    alcool: "tout",
    entreprise: "proxiad",
    stack: "reactjs / react native / angular / spring / nodejs",
    photo:
      "https://media.discordapp.net/attachments/1133662799013355550/1154769592460263504/Screenshot_2023-09-22-14-50-21-73_a63b0f8076346d26cbdc1b971a1da2a7.jpg?width=480&height=642",
    linkedin: "https://www.linkedin.com/in/092155113",
    github: "https://github.com/Ludoph",
  },
  {
    id: 14,
    nom: "beauvois",
    prenom: "marine",
    ville: "la madeleine",
    latlong: [50.654401, 3.0733338],
    hobbies: "sport / ecouter poadcast (relatlongion humaine)",
    music: "de tout / commerciale",
    sport: "bodypump / fitness / cardio",
    jv: "zelda / mario",
    serie: "drama indien / asiatique",
    manga: "shojo / marvel comics",
    platlong: "cuisine asiatique",
    boisson: "the chai",
    alcool: "cocktail",
    entreprise: "darmart",
    stack: "cobol / ruby / rex",
    photo:
      "https://media.licdn.com/dms/image/D4E03AQFmbX6lwzdTFg/profile-displayphoto-shrink_800_800/0/1670926042356?e=1700697600&v=beta&t=9mPbuMQ9j9_FiJOyC-xywvxnzax9myyYeNmbiLfRAFE",
    linkedin: "https://www.linkedin.com/in/marine-beauvois/",
    github: "https://github.com/mbeauvois",
  },
];
